version: "3.8"

services:
  mysqldb:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=krowdyuser
      - MYSQL_PASSWORD=krowdypassword
      - MYSQL_DATABASE=krowdydb
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db:/var/lib/mysql
  app:
    build: ./
    ports:
      - "8085:8085"
    depends_on:
      - mysqldb
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=krowdydb
      - DB_PORT=3306

volumes:
  db:
